### ISSUE TITLE
NullReferenceException thrown while executing merger.csx

### ISSUE THREAD

**Issue by gullswing** [Skirlez/void-stranger-endless-void#1]
using the latest [bleeding-edge build](https://github.com/krzys-h/UndertaleModTool/releases/tag/bleeding-edge) of Undertale Mod Tool.

`NullReferenceException` is thrown on both the GUI and CLI versions of UMT when trying to execute merger.csx (though the GUI version omits the UndertaleModCli line, only showing the merger.csx lines).

stack trace below:

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at UndertaleModCli.Program.GetDecompiledText(UndertaleCode code, GlobalDecompileContext context) in D:\a\UndertaleModTool\UndertaleModTool\UndertaleModCli\Program.UMTLibInherited.cs:line 420
   at Submission#0.applyPatches(String codeEntryName, String patches) in C:\Users\gull\Documents\voidstranger-itch\merger.csx:line 149
   at Submission#0.<<Initialize>>d__0.MoveNext() in C:\Users\gull\Documents\voidstranger-itch\merger.csx:line 140
```

**Comment by skirlez** [comment]
Seems like an issue with patches, can't reproduce. Are you sure the patches are all in the right folder, and that that folder is properly referenced in the script? I'm really not sure what could cause this.

**Comment by gullswing** [comment]
the patches are all in the correct folder, and the folder is properly pointed towards in endlessVoidPatchesPath. double-checked by getting the latest version of endless void and re-replacing the default paths with the ones i'm using in merger.csx.

i also tried moving the whole thing to a different folder, updating the paths in merger, and running it out of there - no dice.

**Comment by skirlez** [comment]
A possible cause could be the version. Are you on the latest version of Void Stranger (1.0.5)? I think one of the updates created a code entry I am patching.

If you are, please try using this version that skips any patch it can't find the code entry of. It will tell you which one it is.
GitHub won't let me upload .csx files, so please change the file extension manually.
[merger.txt](https://github.com/Skirlez/void-stranger-endless-void/files/13164731/merger.txt)

**Comment by Skirlez** [comment]
> A possible cause could be the version. Are you on the latest version of Void Stranger (1.0.5)? I think one of the updates created a code entry I am patching.
> 
> If you are, please try using this version that skips any patch it can't find the code entry of. It will tell you which one it is. GitHub won't let me upload .csx files, so please change the file extension manually. [merger.txt](https://github.com/Skirlez/void-stranger-endless-void/files/13164731/merger.txt)

**Comment by skirlez** [comment]
Found out this happens if you run the script on Endless Void's data.win and not Void Stranger's, so make sure you're not doing that.

**Comment by gullswing** [comment]
> A possible cause could be the version. Are you on the latest version of Void Stranger (1.0.5)? I think one of the updates created a code entry I am patching.
> 
> If you are, please try using this version that skips any patch it can't find the code entry of. It will tell you which one it is. GitHub won't let me upload .csx files, so please change the file extension manually. [merger.txt](https://github.com/Skirlez/void-stranger-endless-void/files/13164731/merger.txt)

i am on the latest version of VS, yes. grabbed the latest version of endless-void, added the patch-skipper to the merger script. herei's the outputs:

```
Attempting to execute '1C:\Users\gull\voidstranger-itch\merger.csx'...
Entry gml_GlobalScript_ev_prepare_level not found, skipping
Entry gml_GlobalScript_ev_prepare_level_patched not found, skipping
i'm done
```

the data.win i am running this on *is* void stranger's - though since you're referencing Endless Void's own data.win i've finally realized that the issue has probably been that i've forgotten to compile EV myself. (in which case, this one is absolutely my bad -- oops, apologies for the trouble, will be closing once i can confirm this is what's going on.)

**Comment by gullswing** [comment]
... that does... not appear to have done it. still getting issues with prepare_level and prepare_level_patched.

**Comment by skirlez** [comment]
gml_GlobalScript_ev_prepare_level has been renamed to gml_GlobalScript_ev_prepare_level_patched in the latest commit, so i'm not sure why you have both patches in the folder. After running the script in UndertaleModTool, can you search for gml_GlobalScript_ev_prepare_level_patched? does it really not show up? (If patching failed it should still be there, but empty)

**Comment by gullswing** [comment]
removed the old prepare_level from the folder. patchless really doesn't show up with either the patch-skipping or the skipless merger, even after running the script - it's a total noshow.

**Comment by skirlez** [comment]
Not sure I understand. prepare_level_patched does not show up? Do all the other assets prefixed with \_ev\_ show up properly? 

The only things that I can think of that could somehow do this is either UndertaleModCli (I didn't test on it, and have experienced some unique bugs with it before) or the GameMaker runtime version used to compile the editor being mismatched with Void Stranger's (make sure it matches the IDE version in the readme)

**Comment by skirlez** [comment]
Fixed ‼️
