### ISSUE TITLE
Incorrect pit/bg sprite behavior with walls and chests

### ISSUE THREAD

**Issue by Fayti1703** [Skirlez/void-stranger-endless-void#16]
All wall tiles and the chest tile do not render the "bottom of the tile" sprite correctly. Specifically:
* When removing the tile below them, the sprite is missing for 1 step.
* No sprite is shown below glass tiles:
![image](https://github.com/user-attachments/assets/6b6199ca-544e-44ea-8593-f5c4cbc18231)
(`2|R2FwIFRlc3Q=||bXNjXzAwMQ==|RmF5dGkxNzAz|68644969983|||0|ptX28flX5ptX9flX15glmnxpfscrexdfblwa04mw04dw04ew04st00glX14flX28|emX46jbemcf0emX63plemX13`)

For chests in particular, this can be fixed by spawning a floor tile underneath them (vanilla rooms typically have such a tile -- though there are exceptions, such as B076 (as of v1.1.1), which result in the same behavior). I'm not sure what the best way for fixing this with walls is, however.

**Comment by skirlez** [comment]
Thank you for opening this issue.
Funnily enough, I also accidentally fixed the sprite not showing up for 1 step with this implementation.
