### ISSUE TITLE
Not a real issue: about GM runtime version.

### ISSUE THREAD

**Issue by sinister-kid** [Skirlez/void-stranger-endless-void#19]
How did you get it was build with 2023.4.0.113 runtime version? I was not able to get it using the UMT (was telling me 2023.6...) I want to mod another GM game and it would be really useful to know.

Aside that, thanks for this repo work, will be really useful to translate the game to spanish and also trying to make it run properly on Vita!

Sorry to use the issues channel this way... Didn't know how to ask.

**Comment by skirlez** [comment]
UMT 0.6.1.0 does show 2023.6 for me as well. I think some older version showed 2023.4, and everything worked so I assumed it was correct. Maybe I should upgrade the version (or at least update the readme)

I'm happy to hear my work was useful! I think the [System Erasure Discord](https://steamcommunity.com/app/2121980/discussions/0/4333104322152879496/) would be interested in those two projects, and they'd likely be able to assist you if you want. (EDIT: I probably misread... the game you're translating/porting is the other game, not Void Stranger. Oops)

**Comment by sinister-kid** [comment]
Hello again! No you didn't misread, is this game I want to translate/port, it's somehow already "playable" on Vita with yoyoloader, but only 15fps, really slow... So I want to fine tune it to make it the real thing.

I think 2023.4 is the real version, I need to try to verify. With 2023.6 was not working for me on 1.1.1 (1.1.0 either), so I was around 1.0.6 game version - 2022.6 runtime.

And there is this other game I want to work on sometime (Hyper Light Drifter SE) which UMT is showing 2023.6 but I don't trust.

I'll check the Discord for sure!!! Thanks again :)
